DROP TABLE RECORDS;


CREATE TABLE ALBUMS(
	ALBUM_ID BIGINT(20) AUTO_INCREMENT,
	TITLE VARCHAR(255),
	CONSTRAINT FK_ALBUMS PRIMARY KEY (ALBUM_ID)
);



CREATE TABLE SONGS_ON_ALBUMS (
    SONG_ID BIGINT(20) NOT NULL,
    ALBUM_ID BIGINT(20) NOT NULL,
    POSITION INTEGER NOT NULL,
    CONSTRAINT FK_SONG_ID FOREIGN KEY (SONG_ID) REFERENCES SONGS(SONG_ID),
    CONSTRAINT FK_ALBUM_ID FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ALBUM_ID)
);