CREATE TABLE SONGS(
    SONG_ID BIGINT(20) AUTO_INCREMENT,
    TITLE VARCHAR(255),
    CONSTRAINT FK_SONGS PRIMARY KEY (SONG_ID)
);

CREATE TABLE RECORDS(
					  RECORD_ID BIGINT(20) AUTO_INCREMENT,
					  TITLE VARCHAR(255),
					  CONSTRAINT FK_RECORDS PRIMARY KEY (RECORD_ID)
);

